package gamelogic;

import java.io.Serializable;

import gamelogic.events.*;

/**
 * the character that users can play as who can use the gun to quickly kill enemies
 * @author brownmax1
 *
 */
public class FighterPlayerStrategy implements CharacterStrategy {
	
	private final int BULLET_DAMAGE = 200;

	
	//USED TO CONVERT THE CLIENT INPUT EVENTS GENERATED BY KEY PRESSES AND CLICKS INTO THE GAME EVENTS RELEVANT TO THIS STRATEGY
	@Override
	public PlayerEvent createCharacterEvent(ClientGeneratedEvent tempClientEvent) {
		//we need to modify movement keys because some characters might move more/less
		if(tempClientEvent instanceof DownPushedEvent){
			return new PlayerMoveDown(tempClientEvent.getUid());
		}else if(tempClientEvent instanceof UpPushedEvent){
			return new PlayerMoveUp(tempClientEvent.getUid());
		}else if(tempClientEvent instanceof LeftPushedEvent){
			return new PlayerMoveLeft(tempClientEvent.getUid());
		}else if(tempClientEvent instanceof RightPushedEvent){
			return new PlayerMoveRight(tempClientEvent.getUid());
		}
		//we need to modify action/ability/attack keys because different characters do this differently
		else if(tempClientEvent instanceof Action1PushedEvent || tempClientEvent instanceof Action2PushedEvent){//action 1 for fighter is attempt to shoot
			return new ShootGunEvent(tempClientEvent.getUid(), this.BULLET_DAMAGE);
		}
		//in the case that it is some other kind of event that is consistent between different characters, return it as is. (e.g. PlayerSelectInvSlot1 is a ClientGeneratedEvent and a PlayerEvent
		//sanity checkkk
		assert(tempClientEvent instanceof PlayerDropEvent || tempClientEvent instanceof PlayerPickupEvent || tempClientEvent instanceof InventorySelectionEvent || tempClientEvent instanceof CarrierOpenCloseEvent || tempClientEvent instanceof RotateMapClockwise || tempClientEvent instanceof PlayerHealEvent):"this kind of event not supported atm in the strategy converter";
		return (PlayerEvent) tempClientEvent;
	}
//TODO: implement getMeleeHit() method etc
	//need to think about how damagin system will work etc actually


	//JOSH ADDED THIS
	@Override
	public String toString(){
		return "Fighter_Strategy";
	}
}
