package gamelogic.events;
/**
 * an event generated by the client's key pushes/clicks etc
 * these may be translated to events individual to that player's character on the
 * server side using the strategy  pattern
 * @author user
 *
 */
public interface ClientGeneratedEvent {

	abstract public int getUid();


}
